class_name SimStatus
extends RefCounted
## Release-safe, first-error-wins status for deterministic simulation work.
##
## Checked operations return neutral values after latching an error. A caller
## must compute into a temporary step buffer and commit authoritative state only
## when `is_ok()` remains true. Keeping diagnostics numeric makes this status
## safe to copy into deterministic failure reports without dynamic payloads.

# Deterministic diagnostic IDs may be persisted in failure reports. Never
# reorder or reuse a value; new IDs are appended with an explicit number.
enum Code {
	OK = 0,
	INVALID_ARGUMENT = 1,
	INVALID_RANGE = 2,
	INT64_OVERFLOW = 3,
	DIVISION_BY_ZERO = 4,
	NEGATIVE_SQRT = 5,
	ZERO_LENGTH = 6,
	INVALID_RNG_STATE = 7,
	RNG_COUNTER_OVERFLOW = 8,
	DUPLICATE_ID = 9,
	NOT_FOUND = 10,
	COUNTER_EXHAUSTED = 11,
	INVALID_SIM_STATE = 12,
	INVALID_POLYGON = 13,
	SIM_LIMIT_EXCEEDED = 14,
	UNRESOLVED_CONTACT = 15,
	UNSUPPORTED_SCHEMA = 16,
	INVALID_SNAPSHOT = 17,
	INVALID_BATTLE_STATE = 18,
	INVALID_PHASE = 19,
	NO_ELIGIBLE_ACTOR = 20,
	RESOLVE_DEADLOCK = 21,
	INVALID_LAUNCH_COMMAND = 22,
	INVALID_AIM_INPUT = 23,
	PREDICTION_LIMIT_EXCEEDED = 24,
	INVALID_COMBATANT = 25,
	INVALID_DAMAGE_CONTEXT = 26,
	INVALID_COLLISION_FACT = 27,
	INVALID_TRIGGER_RECORD = 28,
	TRIGGER_LIMIT_EXCEEDED = 29,
	INVALID_MOTION_CREDIT = 30,
	INVALID_BATTLE_RESULT = 31,
	INVALID_GRAYBOX_FIXTURE = 32,
	BATTLE_TURN_LIMIT = 33,
	BATCH_DETERMINISM_MISMATCH = 34,
	INVALID_BATTLE_REPORT = 35,
	INVALID_ABILITY_BINDING = 36,
	INVALID_EFFECT_DEFINITION = 37,
	INVALID_EFFECT_TARGET = 38,
	EFFECT_LIMIT_EXCEEDED = 39,
	EFFECT_APPLICATION_FAILED = 40,
	CONTENT_FINGERPRINT_MISMATCH = 41,
	INVALID_STATUS_DEFINITION = 42,
	INVALID_STATUS_INSTANCE = 43,
	STATUS_LIMIT_EXCEEDED = 44,
	INVALID_MODIFIER_DEFINITION = 45,
	MODIFIER_RANGE_VIOLATION = 46,
	INVALID_SYNERGY_TALLY = 47,
	INVALID_PIECE_IDENTITY = 48,
	INVALID_ATTACH_LINK = 49,
	DUPLICATE_ATTACH_LINK = 50,
	ATTACH_LIMIT_EXCEEDED = 51,
	INVALID_SPAWN_REQUEST = 52,
	SPAWN_LIMIT_EXCEEDED = 53,
	INVALID_TRANSFORM_TARGET = 54,
	TRANSFORM_LIMIT_EXCEEDED = 55,
	INVALID_TRANSFORM_REQUEST = 56,
}

enum Operation {
	NONE = 0,
	FIX_FROM_INT = 1,
	FIX_FROM_RATIO = 2,
	FIX_ADD = 3,
	FIX_SUB = 4,
	FIX_NEGATE = 5,
	FIX_ABS = 6,
	FIX_INT_MUL = 7,
	FIX_MUL = 8,
	FIX_DIV = 9,
	FIX_ROUND_DIV = 10,
	FIX_TRUNC_DIV = 11,
	FIX_FLOOR_DIV = 12,
	FIX_CEIL_DIV = 13,
	FIX_CLAMP = 14,
	FIX_SQRT = 15,
	VEC_DOT = 16,
	VEC_LENGTH = 17,
	VEC_NORMALIZE = 18,
	VEC_LENGTH_COMPARE = 19,
	LUT_SAMPLE = 20,
	U32_ADD = 21,
	U32_MULTIPLY = 22,
	U32_ROTATE = 23,
	RNG_COPY = 24,
	RNG_DERIVE = 25,
	RNG_RESTORE = 26,
	RNG_STATE_READ = 27,
	RNG_DRAW = 28,
	RNG_RANGE = 29,
	RNG_CHANCE = 30,
	BODY_CREATE = 31,
	ZONE_CREATE = 32,
	ZONE_CONTAINS = 33,
	EVENT_CREATE = 34,
	WORLD_CREATE = 35,
	WORLD_ADD_BODY = 36,
	WORLD_ADD_ZONE = 37,
	WORLD_REMOVE_BODY = 38,
	WORLD_REMOVE_ZONE = 39,
	WORLD_QUEUE_SPAWN = 40,
	WORLD_STEP = 41,
	WORLD_COPY = 42,
	WORLD_EVENT_APPEND = 43,
	WORLD_EVENT_CONSUME = 44,
	WORLD_BODY_UPDATE = 45,
	WORLD_RNG_DRAW = 46,
	POLYGON_CREATE = 47,
	POLYGON_POINT_QUERY = 48,
	POLYGON_SEGMENT_QUERY = 49,
	COLLISION_SUBSTEPS = 50,
	COLLISION_CIRCLE = 51,
	COLLISION_WALL = 52,
	WORLD_BOUNDARY_CONFIG = 53,
	SNAPSHOT_CAPTURE = 54,
	SNAPSHOT_ENCODE = 55,
	SNAPSHOT_RESTORE = 56,
	HASH_SHA256 = 57,
	WORLD_RESTORE = 58,
	SNAPSHOT_DECODE = 59,
	WORLD_COMMIT_SPAWNS = 60,
	WORLD_QUIESCENCE = 61,
	WORLD_STEP_POLICY = 62,
	PARTICIPANT_CREATE = 63,
	CTB_SELECT = 64,
	CTB_PREVIEW = 65,
	BATTLE_CREATE = 66,
	BATTLE_COPY = 67,
	BATTLE_STATE_READ = 68,
	BATTLE_QUEUE_MUTATION = 69,
	BATTLE_MUTATION_BARRIER = 70,
	BATTLE_START_COMPLETE = 71,
	BATTLE_TURN_START_COMPLETE = 72,
	BATTLE_AIM_CANCEL = 73,
	BATTLE_ACTION_COMMIT = 74,
	BATTLE_ACTOR_INTERRUPT = 75,
	BATTLE_RESOLVE_ADVANCE = 76,
	BATTLE_TURN_END_COMPLETE = 77,
	BATTLE_CHECK_APPLY = 78,
	BATTLE_SNAPSHOT_CAPTURE = 79,
	BATTLE_SNAPSHOT_ENCODE = 80,
	BATTLE_SNAPSHOT_DECODE = 81,
	BATTLE_SNAPSHOT_RESTORE = 82,
	LAUNCH_COMMAND_CREATE = 83,
	LAUNCH_COMMAND_ENCODE = 84,
	LAUNCH_COMMAND_DECODE = 85,
	AIM_QUANTIZE = 86,
	LAUNCH_VELOCITY_SOLVE = 87,
	LAUNCH_COMMIT = 88,
	TRAJECTORY_PREDICT = 89,
	COMBATANT_CREATE = 90,
	DAMAGE_CONTEXT_CREATE = 91,
	DAMAGE_RESOLVE = 92,
	COLLISION_FACT_READ = 93,
	BATTLE_DAMAGE_EVENT = 94,
	BATTLE_COOLDOWN_UPDATE = 95,
	WORLD_DESTROY_BODY = 96,
	TRIGGER_RECORD_CREATE = 97,
	TRIGGER_ENQUEUE = 98,
	TRIGGER_DRAIN = 99,
	BATTLE_TRIGGER_READ = 100,
	BATTLE_MOTION_CREDIT = 101,
	BATTLE_RESULT_RESOLVE = 102,
	BATTLE_RANDOM = 103,
	GRAYBOX_FIXTURE_LOAD = 104,
	BATTLE_SHOT_SUPPLY = 105,
	BATTLE_DRIVER_ADVANCE = 106,
	BATTLE_REPORT_CREATE = 107,
	BATCH_COMPARE = 108,
	ABILITY_BIND = 109,
	ABILITY_CONDITION_EVALUATE = 110,
	ABILITY_TARGET_SELECT = 111,
	EFFECT_RESOLVE_TRANSITION = 112,
	EFFECT_APPLY = 113,
	CONTENT_SNAPSHOT_VALIDATE = 114,
	STATUS_APPLY = 115,
	STATUS_REMOVE = 116,
	STATUS_EXPIRE = 117,
	SYNERGY_TALLY_BUILD = 118,
	MODIFIER_AGGREGATE = 119,
	EFFECTIVE_STAT_RESOLVE = 120,
	BATTLE_PHYSICAL_STATS_APPLY = 121,
	BATTLE_PIECE_IDENTITY_READ = 122,
	WORLD_ADD_LINK = 123,
	WORLD_REMOVE_LINK = 124,
	WORLD_RESOLVE_LINKS = 125,
	BATTLE_DYNAMIC_SPAWN = 126,
	BATTLE_TRANSFORM = 127,
	BATTLE_ATTACH = 128,
	BATTLE_EXPIRE = 129,
}

var _code: int = Code.OK
var _operation: int = Operation.NONE
var _detail_a: int = 0
var _detail_b: int = 0


func is_ok() -> bool:
	return _code == Code.OK


func code() -> int:
	return _code


func operation() -> int:
	return _operation


func detail_a() -> int:
	return _detail_a


func detail_b() -> int:
	return _detail_b


func fail(
		p_code: int,
		p_operation: int,
		p_detail_a: int = 0,
		p_detail_b: int = 0
) -> void:
	if not is_ok():
		return
	_code = p_code
	_operation = p_operation
	_detail_a = p_detail_a
	_detail_b = p_detail_b


func copy() -> SimStatus:
	var result: SimStatus = SimStatus.new()
	result._code = _code
	result._operation = _operation
	result._detail_a = _detail_a
	result._detail_b = _detail_b
	return result
