#!/usr/bin/env python3
"""Generate Flickstone's checked-in deterministic quarter-wave sine LUT.

The generator uses Decimal Taylor evaluation and a checked-in decimal PI value,
so output does not depend on the platform C math library. The generated GDScript
contains both the 4,097 Q47.16 samples and the small lookup/interpolation API.
"""
from __future__ import annotations

import argparse
import os
import tempfile
from decimal import Decimal, ROUND_HALF_UP, localcontext
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO_ROOT / "src" / "core" / "sim" / "fix_trig_lut.gd"

SCALE = 65_536
INTERVALS = 4_096
DECIMAL_PI = Decimal(
    "3.141592653589793238462643383279502884197169399375105820974944592307816406286"
    "2089986280348253421170679"
)


def _sin_decimal(value: Decimal) -> Decimal:
    """Sine on [0, pi/2], evaluated with deterministic Decimal arithmetic."""
    if value == 0:
        return Decimal(0)
    squared = value * value
    term = value
    total = value
    n = 1
    threshold = Decimal(1).scaleb(-90)
    while True:
        term = -(term * squared) / Decimal((2 * n) * (2 * n + 1))
        total += term
        if abs(term) < threshold:
            return +total
        n += 1


def generate_values() -> list[int]:
    with localcontext() as context:
        context.prec = 110
        quarter_turn = DECIMAL_PI / Decimal(2)
        values: list[int] = []
        for index in range(INTERVALS + 1):
            angle = quarter_turn * Decimal(index) / Decimal(INTERVALS)
            scaled = _sin_decimal(angle) * Decimal(SCALE)
            values.append(int(scaled.to_integral_value(rounding=ROUND_HALF_UP)))
    if values[0] != 0 or values[-1] != SCALE:
        raise RuntimeError("generated LUT endpoints are invalid")
    if any(left > right for left, right in zip(values, values[1:])):
        raise RuntimeError("generated quarter-wave LUT is not monotonic")
    return values


def _render_values(values: list[int]) -> str:
    lines: list[str] = []
    width = 16
    for start in range(0, len(values), width):
        chunk = ", ".join(str(value) for value in values[start : start + width])
        lines.append(f"\t{chunk},")
    return "\n".join(lines)


def render_gdscript(values: list[int]) -> str:
    table = _render_values(values)
    return f'''# GENERATED by res://src/tools/generate_fix_trig_lut.py. DO NOT EDIT.
class_name FixTrigLut
extends RefCounted
## Quarter-wave Q47.16 sine table and deterministic fixed-angle lookup.

const FULL_TURN: int = 65536
const HALF_TURN: int = 32768
const QUARTER_TURN: int = 16384
const ANGLE_MASK: int = 0xFFFF
const LUT_INTERVALS: int = 4096
const LUT_STEP: int = 4

const _QUARTER_SIN_RAW: Array[int] = [
{table}
]


static func _sample_quarter_raw(quarter_angle: int, status: SimStatus) -> int:
\tif not status.is_ok():
\t\treturn 0
\tif quarter_angle < 0 or quarter_angle > QUARTER_TURN:
\t\tstatus.fail(
\t\t\tSimStatus.Code.INVALID_RANGE,
\t\t\tSimStatus.Operation.LUT_SAMPLE,
\t\t\tquarter_angle,
\t\t\tQUARTER_TURN
\t\t)
\t\treturn 0
\tvar index: int = quarter_angle >> 2
\tif index == LUT_INTERVALS:
\t\treturn _QUARTER_SIN_RAW[LUT_INTERVALS]
\tvar remainder: int = quarter_angle & (LUT_STEP - 1)
\tvar lower: int = _QUARTER_SIN_RAW[index]
\tif remainder == 0:
\t\treturn lower
\tvar upper: int = _QUARTER_SIN_RAW[index + 1]
\treturn lower + FixMath.round_div_int(
\t\t(upper - lower) * remainder, LUT_STEP, status
\t)


static func wrap_angle(angle: int) -> int:
\treturn angle & ANGLE_MASK


static func sin_raw(angle: int, status: SimStatus) -> int:
\tif not status.is_ok():
\t\treturn 0
\tvar wrapped: int = angle & ANGLE_MASK
\tvar quadrant: int = wrapped >> 14
\tvar offset: int = wrapped & (QUARTER_TURN - 1)
\tmatch quadrant:
\t\t0:
\t\t\treturn _sample_quarter_raw(offset, status)
\t\t1:
\t\t\treturn _sample_quarter_raw(QUARTER_TURN - offset, status)
\t\t2:
\t\t\treturn -_sample_quarter_raw(offset, status)
\t\t_:
\t\t\treturn -_sample_quarter_raw(QUARTER_TURN - offset, status)


static func cos_raw(angle: int, status: SimStatus) -> int:
\treturn sin_raw((angle & ANGLE_MASK) + QUARTER_TURN, status)


static func direction(angle: int, status: SimStatus) -> FixVec2:
\treturn FixVec2.from_raw(cos_raw(angle, status), sin_raw(angle, status))
'''


def _write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    temp_path = Path(temporary)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        temp_path.replace(path)
    finally:
        temp_path.unlink(missing_ok=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the existing output differs instead of rewriting it",
    )
    args = parser.parse_args(argv)

    expected = render_gdscript(generate_values())
    output = args.output.resolve()
    if args.check:
        if not output.exists():
            print(f"[FAIL] LUT output is missing: {output}")
            return 1
        actual = output.read_text(encoding="utf-8")
        if actual != expected:
            print(f"[FAIL] generated LUT is stale: {output}")
            return 1
        print(f"[PASS] generated LUT is current: {output}")
        return 0

    _write_atomic(output, expected)
    print(f"generated {INTERVALS + 1} samples: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
